Repository ComputeCanada/puppet-magic_castle, pull requests merged in 2021-03, with the labels that each got.

#108 Change localscratch seltype from default_t to tmp_t
  site/profile/manifests/slurm.pp
Labels: bug

#103 Define default values for prometheus retention
  data/common.yaml
Labels: enhancement

#110 Refactor mkproject.sh daemon
  site/profile/files/accounts/ipa_create_user.py
  site/profile/files/accounts/mkproject.sh
  site/profile/manifests/accounts.pp
Labels: bug, enhancement

#114 Update eessi cvmfs config
  site/profile/manifests/cvmfs.pp
Labels: enhancement

#115 Replace `glob()` by facts and regex in nfs::server
  site/profile/facts.d/dev_disk.sh
  site/profile/manifests/nfs.pp
Labels: bug
